from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List, Optional
from datetime import datetime, timedelta
import requests
import os
from dotenv import load_dotenv

from database import get_db
from models import User, WeatherData, SavedLocation, IRContent, AlertPreference, AlertHistory
from schemas import WeatherDataResponse, WeatherForecastResponse, SavedLocationResponse, SavedLocationCreate
from .auth import get_current_user
from services.weather_service import WeatherService
from services.multi_agent_ai_service import multi_agent_service
from services.location_search_service import LocationSearchService
from services.harbor_service import harbor_service

load_dotenv()

router = APIRouter()
weather_service = WeatherService()
# Multi-agent AI service is now available globally
location_search_service = LocationSearchService()

@router.get("/current/{latitude}/{longitude}", response_model=WeatherDataResponse)
async def get_current_weather(
    latitude: float,
    longitude: float,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get current weather for a specific location"""
    try:
        weather_data = await weather_service.get_current_weather(latitude, longitude)
        
        # Store in database
        db_weather = WeatherData(
            latitude=latitude,
            longitude=longitude,
            timestamp=datetime.utcnow(),
            temperature=weather_data.get("temperature"),
            humidity=weather_data.get("humidity"),
            wind_speed=weather_data.get("wind_speed"),
            wind_direction=weather_data.get("wind_direction"),
            wave_height=weather_data.get("wave_height"),
            wave_period=weather_data.get("wave_period"),
            visibility=weather_data.get("visibility"),
            pressure=weather_data.get("pressure"),
            weather_condition=weather_data.get("weather_condition"),
            hazard_probabilities=weather_data.get("hazard_probabilities", {})
        )
        db.add(db_weather)
        db.commit()
        
        return WeatherDataResponse(**weather_data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching weather data: {str(e)}")

@router.get("/forecast/{latitude}/{longitude}", response_model=WeatherForecastResponse)
async def get_weather_forecast(
    latitude: float,
    longitude: float,
    days: int = Query(7, ge=1, le=14),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get weather forecast for a specific location"""
    try:
        forecast_data = await weather_service.get_forecast(latitude, longitude, days)
        
        # Generate AI hazard summary using multi-agent system
        hazard_analysis = await multi_agent_service.analyze_hazards({
            "weather_data": forecast_data,
            "location": {"latitude": latitude, "longitude": longitude}
        })
        
        return WeatherForecastResponse(
            location=f"{latitude}, {longitude}",
            current=WeatherDataResponse(**forecast_data["current"]),
            forecast=[WeatherDataResponse(**day) for day in forecast_data["forecast"]],
            hazard_summary=hazard_analysis.get("summary", "No significant hazards detected")
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching forecast: {str(e)}")

@router.get("/locations", response_model=List[SavedLocationResponse])
async def get_saved_locations(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get user's saved locations"""
    locations = db.query(SavedLocation).filter(SavedLocation.user_id == current_user.id).all()
    return locations

@router.post("/locations", response_model=SavedLocationResponse)
async def save_location(
    location: SavedLocationCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Save a new location for the user.

    Accepts only the client-provided fields (name, latitude, longitude, location_type).
    ID and created_at are generated by the database and returned in the response model.
    """
    db_location = SavedLocation(
        user_id=current_user.id,
        name=location.name,
        latitude=location.latitude,
        longitude=location.longitude,
        location_type=location.location_type
    )
    db.add(db_location)
    db.commit()
    db.refresh(db_location)
    return db_location

@router.delete("/locations/{location_id}")
async def delete_saved_location(
    location_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete a saved location for the user"""
    try:
        location = db.query(SavedLocation).filter(
            SavedLocation.id == location_id,
            SavedLocation.user_id == current_user.id
        ).first()
        
        if not location:
            raise HTTPException(status_code=404, detail="Location not found")
        
        # Delete related records first to avoid foreign key constraint issues
        db.query(AlertPreference).filter(AlertPreference.location_id == location_id).delete()
        db.query(AlertHistory).filter(AlertHistory.location_id == location_id).delete()
        
        # Delete the location
        db.delete(location)
        db.commit()
        return {"message": "Location deleted successfully"}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Error deleting location: {str(e)}")

@router.get("/ir-content", response_model=List[dict])
async def get_ir_content(
    latitude: Optional[float] = Query(None),
    longitude: Optional[float] = Query(None),
    db: Session = Depends(get_db)
):
    """Get IR content (government bulletins, warnings) for a location"""
    try:
        # Fetch IR content from external sources
        ir_content = await weather_service.fetch_ir_content(latitude, longitude)
        
        # Store in database
        for content in ir_content:
            db_content = IRContent(
                source=content.get("source"),
                content_type=content.get("type"),
                title=content.get("title"),
                content=content.get("content"),
                location_coverage=content.get("location_coverage"),
                severity=content.get("severity"),
                valid_from=content.get("valid_from"),
                valid_until=content.get("valid_until")
            )
            db.add(db_content)
        
        db.commit()
        return ir_content
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching IR content: {str(e)}")

@router.get("/search-locations")
async def search_locations(
    q: str = Query(..., min_length=2, description="Search query for location"),
    limit: int = Query(10, ge=1, le=20, description="Maximum number of results")
):
    """Search for locations with spelling correction and autocomplete"""
    try:
        results = await location_search_service.search_locations(q, limit)
        return {
            "query": q,
            "results": results,
            "total": len(results)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error searching locations: {str(e)}")

@router.get("/location-coordinates")
async def get_location_coordinates(
    name: str = Query(..., description="Location name to get coordinates for")
):
    """Get coordinates for a specific location name"""
    try:
        coordinates = await location_search_service.get_location_coordinates(name)
        if coordinates:
            return coordinates
        else:
            raise HTTPException(status_code=404, detail="Location not found")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error getting coordinates: {str(e)}")

@router.get("/location-details/{latitude}/{longitude}")
async def get_location_details(
    latitude: float,
    longitude: float
):
    """Get location details using reverse geocoding"""
    try:
        location_details = await weather_service.get_location_details(latitude, longitude)
        return location_details
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching location details: {str(e)}")

@router.get("/hazard-analysis/{latitude}/{longitude}")
async def get_hazard_analysis(
    latitude: float,
    longitude: float,
    db: Session = Depends(get_db)
):
    """Get comprehensive hazard analysis for a location"""
    try:
        # Get current weather and forecast
        current_weather = await weather_service.get_current_weather(latitude, longitude)
        forecast = await weather_service.get_forecast(latitude, longitude, 7)
        
        # Get IR content
        ir_content = await weather_service.fetch_ir_content(latitude, longitude)
        
        # Generate AI analysis using multi-agent system
        analysis = await multi_agent_service.analyze_hazards({
            "current_weather": current_weather,
            "forecast": forecast,
            "ir_content": ir_content,
            "location": {"latitude": latitude, "longitude": longitude}
        })
        
        return {
            "location": {"latitude": latitude, "longitude": longitude},
            "current_weather": current_weather,
            "forecast": forecast,
            "ir_content": ir_content,
            "hazard_analysis": analysis
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error analyzing hazards: {str(e)}")

@router.get("/harbors/search")
async def search_harbors(
    q: str = Query(..., min_length=2, description="Search query for harbors/ports"),
    limit: int = Query(10, ge=1, le=20, description="Maximum number of results")
):
    """Search for harbors and ports"""
    try:
        results = await harbor_service.search_harbors(q, limit)
        return {
            "query": q,
            "results": results,
            "total": len(results)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error searching harbors: {str(e)}")

@router.get("/harbors/nearest")
async def find_nearest_harbor(
    lat: float = Query(..., description="Latitude"),
    lon: float = Query(..., description="Longitude"),
    max_distance: float = Query(200, description="Maximum distance in kilometers")
):
    """Find the nearest harbor to a given location"""
    try:
        harbor = await harbor_service.find_nearest_harbor(lat, lon, max_distance)
        if harbor:
            return harbor
        else:
            raise HTTPException(status_code=404, detail="No harbors found within the specified distance")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error finding nearest harbor: {str(e)}")

@router.get("/harbors/validate")
async def validate_harbor_location(
    lat: float = Query(..., description="Latitude"),
    lon: float = Query(..., description="Longitude")
):
    """Validate if a location is suitable for ocean navigation (harbor/port)"""
    try:
        validation = await harbor_service.validate_harbor_location(lat, lon)
        return validation
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error validating harbor location: {str(e)}")
